
on:
  push:
    branches: ['**']
  release:
    types: [published]

env:
  CI_RELEASE: ${{ github.event_name == 'release' }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      node:18.4.0-bullseye-slim@sha256:f1a1a61d847a80ad05f5ef75ee2e0e4515a7ec21f8eb99280eafe33092384583

    steps:
      - uses: actions/checkout@v2

      - run: |
          apt-get update && apt-get install -y ca-certificates git
          npm ci --no-optional
          npm run build

      - if: env.CI_RELEASE == 'true'
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          [ "$(node -p 'require("./package.json").version')" = "$TAG_NAME" ]
          [ "$(node -p 'require("./package-lock.json").version')" = "$TAG_NAME" ]
          echo //registry.npmjs.org/:_authToken="$NPM_TOKEN" >>.npmrc
          npm publish
